# -*- coding: utf-8 -*-
"""
aikota-font · Phase 1 验证: 自研骨架引擎生成 8 个结构字 TTF
================================================================
字表 (覆盖 独体/左右/上下/包围 结构, 全部走 部件库+摆位+笔形 管线):
  日 日 月 口 国 水 木 山

输出:
  verify_a8.ttf    本引擎生成 (aikota-B 预览)
  渲染 8 字对比图 (本引擎 vs A 路线 Arphic 字体)

跑法:  python gen_verify.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from radicals import RADICALS, RAD_LEFT, RAD_TOP
from layout import part_box, scale_strokes, UPM, BASELINE, TOP

from fontTools.ttLib import TTFont
from fontTools.pens.ttGlyphPen import TTGlyphPen

# ── 字表: 码点 → (结构, 部件序列) ─────────────────────────────
# 部件 → 笔画来源: 独体/全格 用 RADICALS, 左旁用 RAD_LEFT, 上件用 RAD_TOP
CHARS = {
    0x65E5: ('日', 'O', ['日']),       # 日 (独体)
    0x6708: ('月', 'O', ['月']),       # 月
    0x53E3: ('口', 'O', ['口']),       # 口
    0x56FD: ('国', 'O', ['国']),       # 国 (自带外框, 独体含内件)
    0x5C71: ('山', 'O', ['山']),       # 山
    0x6C34: ('水', 'O', ['水']),       # 水
    0x6728: ('木', 'O', ['木']),       # 木
    0x5929: ('天', 'O', ['天']),       # 天
    # 上下结构示范
    0x5B57: ('告', 'T', ['艹', '口']), # 告 = 牛头+口 (草稿, 用 艹+口 近似验证管线)
}

# 部件笔画来源映射
def strokes_for(part):
    if part in RADICALS: return RADICALS[part]
    if part in RAD_LEFT: return RAD_LEFT[part]
    if part in RAD_TOP:  return RAD_TOP[part]
    return None

def build_contours(glyph):
    """码点字形 → [(x,y),...] 轮廓列表. 每个笔画展开成 4 点多边形 (A 路线笔形算法)."""
    import math
    struct, parts = glyph
    # 全格盒: 1000upm, 基线 y=120, 顶 y=880
    boxes = part_box(struct, parts, 0, BASELINE, UPM, TOP - BASELINE)
    # 诊断: 打印每笔画展开前的中轴线 (部件坐标, y 向下局部系)
    if os.environ.get("AIKOTA_DEBUG"):
        import sys
        print(f"  struct={struct} parts={parts}", file=sys.stderr)
        for part, box in zip(parts, boxes):
            st = strokes_for(part)
            if st is None:
                print(f"    part '{part}' 无笔画 (缺库)", file=sys.stderr)
                continue
            for (stk, px, py, dx, dy, w) in scale_strokes(st, box):
                print(f"    part '{part}' type={stk} ({px},{py})->({px+dx},{py+dy}) w={w} box={box}", file=sys.stderr)
    contours = []
    for part, box in zip(parts, boxes):
        st = strokes_for(part)
        if st is None:
            continue
        for (stk, px, py, dx, dy, w) in scale_strokes(st, box):
            x0, y0 = px, py
            x1, y1 = px + dx, py + dy
            length = math.hypot(dx, dy) or 1.0
            ux, uy = dx / length, dy / length
            nx, ny = -uy, ux
            hw = w / 2
            # 起笔端 / 收笔端 半宽 (笔形 taper: 横捺起端尖, 竖撇捺收端尖)
            r0 = {0: 0.4, 1: 1.0, 2: 1.0, 3: 0.4, 4: 1.0, 5: 1.0, 6: 1.0}.get(stk, 1.0)
            r1 = {0: 1.0, 1: 0.4, 2: 0.4, 3: 1.0, 4: 0.4, 5: 1.0, 6: 0.4}.get(stk, 1.0)
            c0 = (x0 + nx * hw * r0, y0 + ny * hw * r0)
            c1 = (x0 - nx * hw * r0, y0 - ny * hw * r0)
            c2 = (x1 - nx * hw * r1, y1 - ny * hw * r1)
            c3 = (x1 + nx * hw * r1, y1 + ny * hw * r1)
            contours.append([c0, c3, c2, c1])
    return contours

def stroke_contour_to_glyph(contours):
    pen = TTGlyphPen(None)
    for c in contours:
        pen.moveTo(c[0])
        for p in c[1:]:
            pen.lineTo(p)
        pen.closePath()
    return pen.glyph()

def build_ttf(path):
    glyphs = {".notdef": None}
    names = [".notdef"]
    cmap = {0: ".notdef"}
    for cp, (name, struct, parts) in CHARS.items():
        gname = f"u{cp:04X}"
        names.append(gname)
        cmap[cp] = gname
        contours = build_contours((struct, parts))
        glyphs[gname] = stroke_contour_to_glyph(contours)

    from fontTools.fontBuilder import FontBuilder
    fb = FontBuilder(UPM, isTTF=True)
    fb.setupGlyphOrder(names)
    fb.setupCharacterMap(cmap)

    from fontTools.ttLib.tables._g_l_y_f import Glyph
    def blank():
        g = Glyph(); g.numberOfContours = 0
        g.xMin = g.yMin = g.xMax = g.yMax = 0
        return g
    glyf = {".notdef": blank()}
    for gname in names[1:]:
        g = glyphs.get(gname)
        glyf[gname] = g if g is not None else blank()
    fb.setupGlyf(glyf, calcGlyphBounds=True)
    metrics = {".notdef": (UPM, 0)} | {g: (UPM, 0) for g in names[1:]}
    fb.setupHorizontalMetrics(metrics)
    fb.setupHorizontalHeader(ascent=880, descent=120)
    fb.setupNameTable({
        "familyName": "aikota-B",
        "styleName": "Scaffold",
        "fullName": "aikota-B Scaffold (Phase 1 draft)",
        "psName": "aikota-B-Scaffold",
        "version": "Version 0.1-draft",
        "copyright": "aikota font engine (B route): skeleton generated by aikota-font toolchain. Draft for review.",
    })
    fb.setupOS2(sTypoAscender=880, sTypoDescender=120, sTypoLineGap=0,
                usWinAscent=882, usWinDescent=120, fsSelection=64, fsType=8)
    from fontTools.ttLib.tables.O_S_2f_2 import Panose
    pn = Panose(); pn.bFamilyType = 2; pn.bCharSet = 1; pn.bProportion = 9
    fb.font["OS/2"].panose = pn
    fb.setupPost(isFixedPitch=1)
    fb.setupHead(fontRevision=1.0, created=3937000000, modified=3937000000)
    fb.save(path)
    return path

if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "verify_a8.ttf")
    build_ttf(out)
    print(f"wrote {out}  ({len(CHARS)} chars from {len(set(p for _,_,ps in CHARS.values() for p in ps))} parts)")
    print("下一步: 渲染 8 字对比图 (本引擎 vs Arphic)")
